creator_cfg: !!python/object:phystem.systems.ring.configs.CreatorCfg
  angle: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - !!python/name:numpy.ndarray ''
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 25
    - !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - false
    - !!binary |
      5RsVE/WUC0DKjUbChUgTQM2yJEODhfs/HjJmyGYO/D/BvqKOLYQMQOu4Inau9ANAiourJ0oj+j9o
      00ohmZoVQOwgF3jNdRdAJMqZqf9s+D+u3v6paJYDQM5MJq6c1hZAu7Yh8JA7+z/fKn73bIj2P0CB
      Om+KQwJAzeiqr48l9z9+KV9ysdcTQASqYml1ygJAlDRLg6shB0B0/faKe4DlP5v3ZdSMLwlAW0rq
      EOioCEA5qDhXvYXwP0D6pj++1PQ/bCycWOCLE0A=
  center:
  - - -28.0
    - -28.0
  - - -14.0
    - -28.0
  - - 0.0
    - -28.0
  - - 14.0
    - -28.0
  - - 28.0
    - -28.0
  - - -28.0
    - -14.0
  - - -14.0
    - -14.0
  - - 0.0
    - -14.0
  - - 14.0
    - -14.0
  - - 28.0
    - -14.0
  - - -28.0
    - 0.0
  - - -14.0
    - 0.0
  - - 0.0
    - 0.0
  - - 14.0
    - 0.0
  - - 28.0
    - 0.0
  - - -28.0
    - 14.0
  - - -14.0
    - 14.0
  - - 0.0
    - 14.0
  - - 14.0
    - 14.0
  - - 28.0
    - 14.0
  - - -28.0
    - 28.0
  - - -14.0
    - 28.0
  - - 0.0
    - 28.0
  - - 14.0
    - 28.0
  - - 28.0
    - 28.0
  num_p: 30
  num_rings: 25
  r:
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
  - 5.0
dynamic_cfg: !!python/object:phystem.systems.ring.configs.RingCfg
  area0: 67.55488834678178
  area_potencial: target_area
  diameter: 1
  exclusion_vol: 1
  k_bend: 2
  mobility: 1
  p0: 3.65
  relax_time: 1
  rot_diff: 0.1
  spring_k: 3
  spring_r: 0.7
  trans_diff: 0.1
  vo: 1
other_cfgs: null
rng_seed: null
run_cfg: !!python/object:phystem.core.run_config.CollectDataCfg
  checkpoint: null
  folder_path: checkpoint
  func: nao salvo
  func_cfg: !!python/object:phystem.systems.ring.collect_pipelines.CheckPointCfg
    num_checkpoints: 10
  func_id: null
  int_cfg: !!python/object:phystem.systems.ring.run_config.IntegrationCfg
    dt: 0.001
    in_pol_checker: !!python/object:phystem.systems.ring.run_config.InPolCheckerCfg
      num_col_windows: 4
      update_freq: 100
    integration_type: !!python/object/apply:phystem.systems.ring.run_config.IntegrationType
    - 0
    num_col_windows: 14
    solver_type: !!python/object/apply:phystem.core.run_config.SolverType
    - 2
    update_type: !!python/object/apply:phystem.core.run_config.UpdateType
    - 2
    windows_update_freq: 1
  tf: 10
space_cfg: !!python/object:phystem.systems.ring.configs.SpaceCfg
  size: 70.0
