creator_cfg: !!python/object:phystem.systems.ring.configs.InvaginationCreatorCfg
  diameter: 1
  height: 8
  length: 15
  num_p: 42
  num_rings: 30
dynamic_cfg: !!python/object:phystem.systems.ring.configs.RingCfg
  adh_force: 25
  area0: 140.37465980792538
  area_potencial: target_area_and_format
  diameter: 1
  k_area: 2
  k_format: 0.1
  k_invasion: 12
  max_dist: 1.166
  mobility: 1
  p0: 3.5449077018
  p0_format: 3.5449077018
  relax_time: 100
  rep_force: 30
  rot_diff: 0.1
  spring_k: 5
  spring_r: 0.7
  trans_diff: 0.0
  vo: 1
other_cfgs:
  invagination: !!python/object:phystem.systems.ring.configs.InvaginationCfg
    bottom_k: 2.5
    upper_k: 15
rng_seed: null
run_cfg: !!python/object:phystem.core.run_config.CollectDataCfg
  checkpoint: null
  folder_path: init_loop
  func: nao salvo
  func_cfg: null
  func_id: null
  int_cfg: !!python/object:phystem.systems.ring.run_config.IntegrationCfg
    dt: 0.001
    in_pol_checker: !!python/object:phystem.systems.ring.run_config.InPolCheckerCfg
      disable: false
      num_col_windows: 10
      num_rows_windows: 10
      update_freq: 100
    integration_type: !!python/object/apply:phystem.systems.ring.run_config.IntegrationType
    - 0
    particle_win_cfg: !!python/object:phystem.systems.ring.run_config.ParticleWindows
      num_cols: 103
      num_rows: 103
      update_freq: 1
    solver_type: !!python/object/apply:phystem.core.run_config.SolverType
    - 2
    update_type: !!python/object/apply:phystem.systems.ring.run_config.UpdateType
    - 4
  tf: 30
space_cfg: !!python/object:phystem.systems.ring.configs.SpaceCfg
  height: 430.5047505077533
  length: 430.5047505077533
