class SelfPropellingCfg:
    def __init__(self, values: dict[str, float]) -> None: ...
    def info() -> None: ...

class RingCfg:
    def __init__(self, values: dict[str, float]) -> None: ...

class InPolCheckerCfg: 
    def __init__(self, num_cols_windows: int, update_freq: int, disable: bool) -> None: ...

class ParticleWindowsCfg:
    def __init__(num_cols: int, num_rows: int, update_freq: int) -> None: ...

class InPolCheckerCfg: 
    def __init__(self, num_cols_windows: int, num_rows_windows: int, update_freq: int, disable: bool) -> None: ...