from phystem.cpp_lib.data_types import PosVec, PyVecList

class Ring:
    def __init__(self, pos0, vel0, self_prop_angle0, dynamic_cfg, 
        size, dt, seed=-1) -> None: ...

    pos: PosVec = ...
    vel: PosVec = ...
    self_prop_vel: PosVec = ...
    self_prop_angle = ...
    
    pos_continuos: PosVec = ...

    pos_t: PyVecList = ...
    graph_points: PyVecList = ...
    
    spring_forces: PosVec = ...
    vol_forces: PosVec = ...
    area_forces: PosVec = ...
    total_forces: PosVec = ...
    
    differences: PosVec = ...

    def update_normal() -> None: ...
    def mean_vel() -> float: ...
    def mean_vel_vec() -> list: ...

class SelfPropelling:
    def __init__(self, pos0, vel0, propelling_cfg, size, dt, num_windows, seed=-1) -> None: ...

    n: int = ...
    pos: PosVec = ...
    vel: PosVec = ...
    propelling_vel: PosVec = ...
    propelling_angle= ...
    py_pos: PyVecList = ...
    
    py_pos: PosVec = ...
    py_vel: PosVec = ...
    py_propelling_vel: PosVec = ...

    random_number: float = ...

    def update_normal() -> None: ...
    def update_windows() -> None: ...
    def mean_vel() -> float: ...
    def mean_vel_vec() -> list: ...