class WindowsManager:
    def __init__(p_pos, num_cols, num_rows, space_size) -> None: ...

    col_size = ...
    row_size = ...
    windows = ...
    capacity = ...
    windows = ...
    windows_ids = ...
    window_neighbor = ...
    windows_center = ...

    def update_window_members(): ...