creator_cfg: !!python/object:phystem.systems.szabo.configs.CreatorCfg
  n: 1000
  r: 20.0
  type: !!python/object/apply:phystem.systems.szabo.configs.CreateType
  - 2
dynamic_cfg: !!python/object:phystem.systems.szabo.configs.SelfPropellingCfg
  max_attractive_force: 0.75
  max_r: 1.0
  max_repulsive_force: 30
  mobility: 1.0
  nabla: 1
  r_eq: 0.8333333333333334
  relaxation_time: 1.0
  vo: 1.0
other_cfgs: null
rng_seed: 40028922
run_cfg: !!python/object:phystem.systems.szabo.run_config.SaveCfg
  checkpoint: null
  dt: 0.01
  duration: 3
  fps: 30
  graph_cfg: !!python/object:phystem.systems.szabo.run_config.GraphCfg
    show_circles: false
  num_frames: 90
  num_steps_frame: 17
  num_windows: 10
  path: ./szabo.gif
  solver_type: !!python/object/apply:phystem.core.run_config.SolverType
  - 2
  speed: 5
  tf: 15.3
  update_type: !!python/object/apply:phystem.core.run_config.UpdateType
  - 2
space_cfg: !!python/object:phystem.systems.szabo.configs.SpaceCfg
  size: 40
