creator_cfg: !!python/object:phystem.systems.ring.configs.CreatorCfg
  angle: []
  center: []
  num_p: 30
  num_rings: 0
  r: null
dynamic_cfg: !!python/object:phystem.systems.ring.configs.RingCfg
  adh_force: 0.75
  area0: 71.61972439179868
  area_potencial: target_area
  diameter: 1
  k_bend: 4
  max_dist: 1.1666
  mobility: 1
  p0: 3.5449077018
  relax_time: 1
  rep_force: 30
  rot_diff: 0.1
  spring_k: 10
  spring_r: 0.7
  trans_diff: 0.1
  vo: 1
other_cfgs:
  stokes: !!python/object:phystem.systems.ring.configs.StokesCfg
    create_length: 9.614606094673166
    flux_force: 0.5
    num_max_rings: 100
    obstacle_r: 10.0
    obstacle_x: 0.0
    obstacle_y: 0.0
    remove_length: 9.614606094673166
rng_seed: null
run_cfg: !!python/object:phystem.core.run_config.CollectDataCfg
  checkpoint: !!python/object:phystem.core.run_config.CheckpointCfg
    configs: nao salvo
    folder_path: data_check
    override_cfgs: true
  folder_path: data_check_2
  func: nao salvo
  func_cfg: !!python/object:pipeline.PipelineCfg
    num_saves: 5
  func_id: null
  int_cfg: !!python/object:phystem.systems.ring.run_config.IntegrationCfg
    dt: 0.001
    in_pol_checker: !!python/object:phystem.systems.ring.run_config.InPolCheckerCfg
      disable: false
      num_col_windows: 8
      num_rows_windows: 7
      update_freq: 50
    integration_type: !!python/object/apply:phystem.systems.ring.run_config.IntegrationType
    - 0
    particle_win_cfg: !!python/object:phystem.systems.ring.run_config.ParticleWindows
      num_cols: 37
      num_rows: 30
      update_freq: 1
    solver_type: !!python/object/apply:phystem.core.run_config.SolverType
    - 2
    update_type: !!python/object/apply:phystem.systems.ring.run_config.UpdateType
    - 3
  tf: 10
space_cfg: !!python/object:phystem.systems.ring.configs.SpaceCfg
  height: 60
  length: 75.0
