creator_cfg: !!python/object:phystem.systems.ring.configs.CreatorCfg
  angle: []
  center: []
  num_p: 15
  num_rings: 0
  r: null
dynamic_cfg: !!python/object:phystem.systems.ring.configs.RingCfg
  adh_force: 20
  area0: 17.90493109794967
  area_potencial: target_area_and_format
  diameter: 1
  k_area: 2
  k_format: 0.03
  k_invasion: 8
  max_dist: 1.05
  mobility: 1
  p0: 3.5449077018
  p0_format: 3.5449077018
  relax_time: 0.5
  rep_force: 12
  rot_diff: 0.1
  spring_k: 8
  spring_r: 0.7
  trans_diff: 0
  vo: 1
other_cfgs:
  stokes: !!python/object:phystem.systems.ring.configs.StokesCfg
    create_length: 4.83378301646785
    flux_force: 1
    num_max_rings: 115
    obs_force: 15
    obstacle_r: 8.417035103302227
    obstacle_x: 0
    obstacle_y: 0
    remove_length: 4.83378301646785
rng_seed: 238531723
run_cfg: !!python/object:phystem.core.run_config.RealTimeCfg
  checkpoint: null
  fps: 60
  graph_cfg: !!python/object:phystem.systems.ring.ui.graphs_cfg.SimpleGraphCfg
    ax_kwargs: {}
    begin_paused: false
    cbar_kwargs: {}
    cell_shape: null
    cpp_is_debug: true
    density_kwargs: {}
    pause_on_high_vel: false
    rings_kwargs:
      s: 6
    show_density: false
    show_rings: true
  int_cfg: !!python/object:phystem.systems.ring.run_config.IntegrationCfg
    dt: 0.01
    in_pol_checker: !!python/object:phystem.systems.ring.run_config.InPolCheckerCfg
      disable: false
      num_col_windows: 12
      num_rows_windows: 6
      update_freq: 50
    integration_type: !!python/object/apply:phystem.systems.ring.run_config.IntegrationType
    - 0
    particle_win_cfg: !!python/object:phystem.systems.ring.run_config.ParticleWindows
      num_cols: 41
      num_rows: 19
      update_freq: 1
    solver_type: !!python/object/apply:phystem.core.run_config.SolverType
    - 2
    update_type: !!python/object/apply:phystem.systems.ring.run_config.UpdateType
    - 3
  num_steps_frame: 81
  ui_settings: !!python/object:phystem.gui_phystem.config_ui.UiSettings
    ControlT: !!python/name:phystem.systems.ring.ui.ui_components.Control ''
    InfoT: !!python/name:phystem.systems.ring.ui.ui_components.Info ''
    always_update: false
    dpi: 130
    left_pannel_size: 0.3
    window_scale: 0.83
space_cfg: !!python/object:phystem.systems.ring.configs.SpaceCfg
  height: 33.66814041320891
  length: 72.14601517116195
